#!/bin/bash
#
# This is executed in a chroot inside the mounted image
#
# Image wil be mounted to <base-dir>/mnt
#
# This sets IP address and hostname
#
# This file is for the node setup, i.e. it will be excuted once for EVERY
# image
#
# DO NOT edit this file. Do have additonal setup code put it in the
# modify_image_node.sh script.
#
# Parameter <image> <base-dir> <nodename> <ip-address> <netmask>
#
# (c) 2010 IBR

IMAGE_FILE=$1
BASE=$2
NODE_NAME=$3
NODE_ADDRESS=$4
NODE_NETMASK=$5

echo "------- Node setup ---------------------------------------------------"

echo "Preparing image in ${IMAGE_FILE} with"
echo "Node name    : ${NODE_NAME}"
echo "Node address : ${NODE_ADDRESS}"
echo "Node netmask : ${NODE_NETMASK}"

if [ ! -e "${IMAGE_FILE}" ]
then
   echo "$0: Can not find image  ${IMAGE_FILE}"
   exit -1
fi

mkdir -p "${BASE}/mnt/"
bash ${BASE}/magicmount.sh "${IMAGE_FILE}" "${BASE}/mnt/"

# switch to chroot
chroot "${BASE}/mnt/" /bin/sh <<EOF

/sbin/uci set system.@system[0].hostname=${NODE_NAME}
/sbin/uci commit system.@system[0].hostname

/sbin/uci set network.lan.ipaddr=${NODE_ADDRESS}
/sbin/uci set network.lan.netmask=${NODE_NETMASK}
/sbin/uci commit network

# close chroot
EOF


#custom setup preparation
echo ">>>>> Custom image setup"
cp ${BASE}/modify_image_node.sh "${BASE}/mnt"
chroot "${BASE}/mnt/" /bin/sh /modify_image_node.sh "${NODE_NAME}"
echo ">>>>> Custom image setup done."

umount "${BASE}/mnt/"

until [ $? -eq 0 ]; do
	sleep 1
	umount "${BASE}/mnt/"
done

echo "------- Node setup done ------------------------------------------------"
