#!/bin/bash
#
# This is executed in a chroot inside the mounted image
#
# Image wil be mounted to <base-dir>/mnt
#
# All files from <base-dir>/overlay will be copied to the chroot
# All packages from <base-dir>/packages will be installed in chroot
#
# This file is for the base setup, i.e. it will be excuted only ONCE and all
# changes done  by this file are copied to all nodes
#
# DO NOT edit this file. Do have additonal setup code put it in the
# modify_image_base.sh script.
#
# Parameter <image file> <base-dir> <ntp-server>
#
# 2010 IBR


IMAGE_FILE=$1
BASE=$2
NTP_SERVER=$3

echo "------- Image setup ---------------------------------------------------"

echo "Preparing image $IMAGE_FILE with"
echo "Base: $BASE"

if [ ! -e "$IMAGE_FILE" ]
then
    echo "$0: Can't see image file $1"
    exit -1
fi

IMAGE_EXT="${IMAGE_FILE##*.}"

if [ ${IMAGE_EXT} == "gz" ]
then
    gunzip -f ${IMAGE_FILE}
    IMAGE_FILE="${IMAGE_FILE%.*}"
fi

if [ ! -d "$BASE" ]
then
    echo "$0: Can not find base directory  $2"
    exit -1
fi

if [ ! -e "$BASE/mnt" ]
then
    mkdir "$BASE/mnt"
fi


# mount the image
bash "$BASE/magicmount.sh" "$IMAGE_FILE" "$BASE/mnt/"


#We need DNS capability in chroot
cp /etc/resolv.conf $BASE/mnt/tmp/resolv.conf

# install packages
echo "Installing packages"
PACKAGES=`cat $BASE/packages.install | grep -v "^#"`

chroot $BASE/mnt /bin/sh -c "mkdir /var/lock"

# add external repository
if [ -e "$BASE/opkg.external" ]; then
    cat $BASE/opkg.external $BASE/mnt/etc/opkg.conf > $BASE/mnt/etc/opkg.conf.new
    mv $BASE/mnt/etc/opkg.conf.new $BASE/mnt/etc/opkg.conf
fi

chroot $BASE/mnt opkg update

for pkg in $PACKAGES
do
    echo "Install $pkg"
    chroot $BASE/mnt /bin/sh -c "opkg install ${pkg}"
done

for pkg in $(ls -1 $BASE/packages)
do
    echo "Install $pkg"
    cp "$BASE/packages/$pkg" "$BASE/mnt/"
done

chroot $BASE/mnt /bin/sh -c "opkg install *.ipk; rm *.ipk"

#copy
echo "Copying overlay"
cp -r -f $BASE/overlay/*  "$BASE/mnt/"
cp -v "$BASE/modify_image_base.sh" "$BASE/mnt/"

#custom setup preparation
echo ">>>>> Custom image setup"
chroot $BASE/mnt /bin/sh /modify_image_base.sh 
echo ">>>>> Custom image setup done."

# remove the setup script
rm "$BASE/mnt/modify_image_base.sh"

# switch to chroot
chroot "$BASE/mnt" /bin/sh -x <<EOF

# network configuration
/sbin/uci del network.lan.type
/sbin/uci del network.lan.ipaddr
/sbin/uci del network.lan.netmask
/sbin/uci set network.lan.ifname=eth1
/sbin/uci set network.lan.proto=static

/sbin/uci rename network.\$(/sbin/uci add network interface)=hydra
/sbin/uci set network.hydra.ifname=eth0
/sbin/uci set network.hydra.proto=dhcp

# set time-sync server
/sbin/uci set system.ntp.server=${NTP_SERVER}

/sbin/uci commit

# change permissions
/bin/chmod 0755 /etc/init.d/hnd

# enable node initrc
/etc/init.d/hnd enable

# close chroot
EOF

# unmount the image
umount  "$BASE/mnt/"

echo "------- Image setup done ------------------------------------------------"
